name: Go/Lint

on:
  push:
    branches: ["**"]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests With Compose
        run: docker compose run --rm --build this golangci-lint run