name: Go/Test

on: 
  push:
    branches: ["**"]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build With Compose
        run: make build

      - name: Run Tests With Compose
        run: make test